-- apps/api/drizzle/0001_ssh_keys.sql
-- Usage: generated by `pnpm db:generate`; applied by `pnpm db:migrate`.
-- Adds ssh_keys and servers.ssh_public_keys. Do not edit once applied anywhere.
CREATE TABLE "ssh_keys" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" uuid NOT NULL,
	"name" text NOT NULL,
	"public_key" text NOT NULL,
	"fingerprint" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ssh_keys_owner_fingerprint_unique" UNIQUE("owner_id","fingerprint")
);
--> statement-breakpoint
ALTER TABLE "servers" ADD COLUMN "ssh_public_keys" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "ssh_keys" ADD CONSTRAINT "ssh_keys_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;