-- apps/api/drizzle/0002_customer_projects.sql
-- Usage: generated by `pnpm db:generate`; applied by `pnpm db:migrate`.
-- Adds per-customer VHI project ids and quota overrides. Do not edit once applied anywhere.
ALTER TABLE "servers" ADD COLUMN "vhi_project_id" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "vhi_project_id" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "quotas" jsonb;