-- apps/api/drizzle/0005_firewall.sql
-- Usage: generated by `pnpm db:generate`; applied by `pnpm db:migrate`.
-- Adds per-customer inbound firewall rules. Do not edit once applied anywhere.
CREATE TYPE "public"."firewall_protocol" AS ENUM('tcp', 'udp', 'icmp', 'any');--> statement-breakpoint
CREATE TABLE "firewall_rules" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"protocol" "firewall_protocol" NOT NULL,
	"port_min" integer,
	"port_max" integer,
	"cidr" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "firewall_rules" ADD CONSTRAINT "firewall_rules_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "firewall_rules_user_idx" ON "firewall_rules" USING btree ("user_id");