-- apps/api/drizzle/0007_volumes.sql
-- Usage: generated by `pnpm db:generate`; applied by `pnpm db:migrate`.
-- Adds data volumes and lets usage records point at a volume instead of a server. Do not edit once applied anywhere.
CREATE TYPE "public"."volume_status" AS ENUM('creating', 'available', 'attaching', 'attached', 'detaching', 'deleting', 'deleted', 'error');--> statement-breakpoint
CREATE TABLE "volumes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" uuid NOT NULL,
	"name" text NOT NULL,
	"size_gb" integer NOT NULL,
	"status" "volume_status" DEFAULT 'creating' NOT NULL,
	"status_message" text,
	"server_id" uuid,
	"vhi_project_id" text,
	"vhi_volume_id" text,
	"billing_started_at" timestamp with time zone,
	"billed_until" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "volumes_vhi_volume_id_unique" UNIQUE("vhi_volume_id")
);
--> statement-breakpoint
ALTER TABLE "usage_records" ALTER COLUMN "server_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "usage_records" ADD COLUMN "volume_id" uuid;--> statement-breakpoint
ALTER TABLE "volumes" ADD CONSTRAINT "volumes_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "volumes" ADD CONSTRAINT "volumes_server_id_servers_id_fk" FOREIGN KEY ("server_id") REFERENCES "public"."servers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "volumes_owner_idx" ON "volumes" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "volumes_server_idx" ON "volumes" USING btree ("server_id");--> statement-breakpoint
ALTER TABLE "usage_records" ADD CONSTRAINT "usage_records_volume_id_volumes_id_fk" FOREIGN KEY ("volume_id") REFERENCES "public"."volumes"("id") ON DELETE no action ON UPDATE no action;